### ISSUE TITLE
AdsInsights's bug

### ISSUE THREAD

**Issue by tanzhuqing** [facebook/facebook-java-ads-sdk#52]
0.4.0  AdsInsights can not get  all breakdown data "age","country","gender","impression_device" and other.

**Comment by amjaliks** [comment]
It is possible still get them in a _hacky_ way `getRawResponseAsJsonObject().get("country").getAsString()`. But it would be nice to get back `getField*()` methods.

**Comment by zhengzhiyuan** [comment]
not only in api can not get those data, the response of insight also has not.

**Comment by root1984** [comment]
Why these field are removed in 0.4.0?

At lease, we need method getField to do this()

**Comment by sang-d** [comment]
age and gender are still missing when parse from APIResponse to AdsInsights

**Comment by JiamingFB** [comment]
this is fixed in latest release

**Comment by ymeymann** [comment]
I am using the latest release and the bug is still there. The only way to get country is with @amjaliks hack.
